<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>DashMaster</RootNamespace>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win10-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<WindowsPackageType>None</WindowsPackageType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Commands\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.8" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Images\dashboard.png" />
		<Resource Include="Images\home.png" />
		<Resource Include="Images\library.png" />
		<Resource Include="Images\record-icon-true.png" />
		<Resource Include="Images\record-icon.png" />
		<Resource Include="Images\settings.png" />
	</ItemGroup>

</Project>